baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Zhenghao (Kevin) Zhu's Personal Website"
  keywords = "personal website, homepage, blog, science, informatics, development, programming, Stony Brook University, Zhenghao Zhu, Zhenghao (Kevin) Zhu, Kevin Zhu"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"


[languages]
  [languages.en]
    title = "Zhenghao (Kevin) Zhu"
    keywords = "personal website, homepage, blog, science, informatics, development, programming, Stony Brook University, Zhenghao Zhu, Zhenghao (Kevin) Zhu, Kevin Zhu"
    copyright = ""  
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /Users/kevin/Home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "Projects"
        name = "Projects"
        url = "/projects"
      
  # Social icons
  [[params.social]]
    name = "resume"
    url = "https://drive.google.com/file/d/19hkDCv6O76GxIZwTzRHhn4BBY_Y4IiFD/view?usp=sharing"

  [[params.social]]
    name = "email"
    url  = "mailto:kevinzhuzhenghao@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ZhenghaoZhu"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/zhuzhenghao/"
# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"